// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package history

import (
	"time"
)

type Answer struct {
	ID           int64
	SessionCode  string
	QuestionText string
	Options      string
	GivenAnswer  string
	AnsweredAt   time.Time
}

type Session struct {
	Code         string
	LastJoinedAt time.Time
}
