// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package history

import (
	"context"
)

const listSessions = `-- name: ListSessions :many
SELECT code, last_joined_at FROM sessions
ORDER BY last_joined_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(&i.Code, &i.LastJoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAnswer = `-- name: SaveAnswer :exec
INSERT INTO answers (session_code, question_text, options, given_answer) 
VALUES (?, ?, ?, ?)
`

type SaveAnswerParams struct {
	SessionCode  string
	QuestionText string
	Options      string
	GivenAnswer  string
}

func (q *Queries) SaveAnswer(ctx context.Context, arg SaveAnswerParams) error {
	_, err := q.db.ExecContext(ctx, saveAnswer,
		arg.SessionCode,
		arg.QuestionText,
		arg.Options,
		arg.GivenAnswer,
	)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (code, last_joined_at) 
VALUES (?, CURRENT_TIMESTAMP)
ON CONFLICT(code) DO UPDATE SET 
    last_joined_at = CURRENT_TIMESTAMP
`

func (q *Queries) UpsertSession(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, upsertSession, code)
	return err
}
